apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: component-manage
version: 0.1.0
annotations:
  "org.opencontainers.image.source": "https://github.com/kweaver-ai/proton"