{
 "title": "A-01_巡检仪表盘",
 "tags": [
  "product",
  "anyrobot",
  "monitor",
  "summary"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds, node)"
    }
   },
   {
    "name": "opensearch_pod",
    "query": {
     "query": "label_values(opensearch_filesystem_data_size_bytes, name)"
    }
   },
   {
    "name": "opensearch_node",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$opensearch_pod\"}, node)"
    }
   },
   { "name": "root", "label": "root", "query": "#OPENSEARCH_VARS_ROOT#" },
   { "name": "hot", "label": "hot", "query": "#OPENSEARCH_VARS_HOT#" },
   { "name": "warm", "label": "warm", "query": "#OPENSEARCH_VARS_WARM#" },
   { "name": "rootDev", "label": "rootDev", "query": "#OPENSEARCH_VARS_ROOTDEV#" },
   { "name": "hotDev", "label": "hotDev", "query": "#OPENSEARCH_VARS_HOTDEV#" },
   { "name": "warmDev", "label": "warmDev", "query": "#OPENSEARCH_VARS_WARMDEV#" },
   { "name": "mem_warning", "query": "#MEM_WARNING#" },
   { "name": "mem_critical", "query": "#MEM_CRITICAL#" },
   { "name": "load1_warning", "query": "#LOAD1_WARNING#" },
   { "name": "load1_critical", "query": "#LOAD1_CRITICAL#" },
   { "name": "load5_warning", "query": "#LOAD5_WARNING#" },
   { "name": "load5_critical", "query": "#LOAD5_CRITICAL#" },
   { "name": "load15_warning", "query": "#LOAD15_WARNING#" },
   { "name": "load15_critical", "query": "#LOAD15_CRITICAL#" },
   { "name": "disk_warning", "query": "#STORAGE_WARNING#" },
   { "name": "disk_critical", "query": "#STORAGE_CRITICAL#" },
   { "name": "cpu_warning", "query": "#CPU_WARNING#" },
   { "name": "cpu_critical", "query": "#CPU_CRITICAL#" }
  ]
 },
 "panels": [
  {
   "title": "说明",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "变量",
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "> 使用仪表盘前，请先正确配置变量。具体如下：\n\n| 变量名 | 当前值 | 描述 |\n| ---- | ---- | ----|\n| node | ${node} | AnyRobot节点 |\n| opensearch_pod | ${opensearch_pod} | opensearch pod名称 |\n| opensearch_node | ${opensearch_node} | opensearch 节点 |\n| root | ${root}\t | 系统分区 |\n| hot | ${hot} | 热数据分区 |\n| warm | ${warm} | 温数据分区 |\n| rootDev | ${rootDev} | 系统存储设备 |\n| hotDev | ${hotDev} | 热数据存储设备 |\n| warmDev | ${warmDev} | 温数据存储设备 |\n\n----\n【请根据服务器实际情况进行配置】\n\n\n"
     }
    }
   ]
  },
  {
   "title": "主机",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "主机数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_exporter_build_info) - sum(up{service=\"node-exporter\"})",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "宕机数",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_exporter_build_info)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "总数",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "资源健康度监控告警",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 2, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "所有主机CPU、负载、内存、存储等资源健康度监控概览",
   "type": "text",
   "gridPos": { "h": 1, "w": 18, "x": 6, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "警告",
   "type": "stat",
   "description": "统计所有主机内存使用率>$mem_warning%,cpu使用率>$cpu_warning%,平均1分钟负载>$load1_warning,平均5分钟负载>$load5_warning,平均15分钟负载>$load15_warning,分区空间使用率>$disk_warning%的事件数量。",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count ( $mem_critical > (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))* 100 >= $mem_warning)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "mem_warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($cpu_critical > 100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))by (node) * 100) >= $cpu_warning)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "cpu_warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($load1_critical > node_load1/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)>= $load1_warning)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "load1_warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($load5_critical > node_load5/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)>= $load5_warning)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "load5_warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($load15_critical > node_load15/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)>= $load15_warning)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "load15_warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($disk_critical > (1-node_filesystem_free_bytes{fstype=~\"ext.*|xfs|nfs\"}/node_filesystem_size_bytes{fstype=~\"ext.*|xfs|nfs\"})*100 >= $disk_warning)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "disk_warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "紧急",
   "type": "stat",
   "description": "统计所有主机内存使用率>$mem_critical%,cpu使用率>$cpu_critical%,平均1分钟负载>$load1_critical,平均5分钟负载>$load5_critical,平均15分钟负载>$load15_critical,分区空间使用率>$disk_critical%的事件数量。",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count ((1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100 >= $mem_critical)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "mem_critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))by (node) * 100) >= $cpu_critical)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "cpu_critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_load1/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)>= $load1_critical)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "load1_critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_load5/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)>= $load5_critical)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "load5_critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_load15/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)>= $load15_critical)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "load15_critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count((1-node_filesystem_free_bytes{fstype=~\"ext.*|xfs|nfs\"}/node_filesystem_size_bytes{fstype=~\"ext.*|xfs|nfs\"})*100 >= $disk_critical)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "disk_critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "CPU、内存、存储分区",
   "type": "grafana-polystat-panel",
   "description": "黄色：CPU使用率>=$cpu_warning%、内存使用率>=$mem_warning%、分区空间使用率>=$disk_warning%\n\n红色：CPU使用率>=$cpu_critical%、内存使用率>=$mem_critical%、分区空间使用率>=$disk_critical%",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "{{ node }}-mem"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))by (node) * 100)",
     "legendFormat": "{{ node }}-cpu"
    },
    {
     "expr": "(1-node_filesystem_free_bytes{fstype=~\"ext.*|xfs|nfs\"}/node_filesystem_size_bytes{fstype=~\"ext.*|xfs|nfs\"})*100",
     "legendFormat": "{{ node }}-disk-{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "grafana-polystat-panel",
   "description": "黄色：1分钟负载>=$load1_warning、5分钟负载>=$load5_warning、15分钟负载>=$load15_warning\n\n红色：1分钟负载>=$load1_critical、5分钟负载>=$load5_critical、15分钟负载>=$load15_critical",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 3 },
   "targets": [
    {
     "expr": "node_load1/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)",
     "legendFormat": "{{ node }}-load_1"
    },
    {
     "expr": "node_load5/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)",
     "legendFormat": "{{ node }}-load_5"
    },
    {
     "expr": "node_load15/on(node) count(node_cpu_seconds_total{mode='system'}) by (node)",
     "legendFormat": "{{ node }}-load_15"
    }
   ]
  },
  {
   "title": "OpenSearch存储",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "存储分区数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_filesystem_size_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"})",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "总数",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "存储分区空间使用率监控告警",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 2, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "所有OpenSearch主机节点存储分区空间使用率监控概览",
   "type": "text",
   "gridPos": { "h": 1, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "警告",
   "type": "stat",
   "description": "空间使用率>=$disk_warning%分区数",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($disk_critical > (1 -node_filesystem_free_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}) * 100 >= $disk_warning )",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "Warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "紧急",
   "type": "stat",
   "description": "空间使用率>=$disk_critical%分区数",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count((1 -node_filesystem_free_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}) * 100 >= $disk_critical )",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "Critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "系统分区",
   "type": "grafana-polystat-panel",
   "description": "黄色：空间使用率>=$disk_warning%\n\n红色：空间使用率>=$disk_critical%",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "(1-node_filesystem_free_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$opensearch_node\",mountpoint=~\"$root\",fstype=~\"ext.*|xfs\"})*100",
     "legendFormat": "{{node}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "热数据分区",
   "type": "grafana-polystat-panel",
   "description": "黄色：空间使用率>=$disk_warning%\n\n红色：空间使用率>=$disk_critical%",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(1-node_filesystem_free_bytes{node=~\"$opensearch_node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$opensearch_node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"})*100",
     "legendFormat": "{{node}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "温数据分区",
   "type": "grafana-polystat-panel",
   "description": "黄色：空间使用率>=$disk_warning%\n\n红色：空间使用率>=$disk_critical%",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "(1-node_filesystem_free_bytes{node=~\"$opensearch_node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$opensearch_node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"})*100",
     "legendFormat": "{{node}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "容器监控总览",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {}
     ]
    },
    {
     "title": "节点数",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 0, "y": 15 },
     "targets": [
      {}
     ]
    },
    {
     "title": "【部署】Pods健康度监控告警",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 4, "y": 15 },
     "targets": [
      {}
     ]
    },
    {
     "title": "【有状态副本集】Pods健康度监控告警",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 8, "y": 15 },
     "targets": [
      {}
     ]
    },
    {
     "title": "【守护进程集】Pods健康度监控告警",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 15 },
     "targets": [
      {}
     ]
    },
    {
     "title": "【K8S组件】Pods健康度监控告警",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 16, "y": 15 },
     "targets": [
      {}
     ]
    },
    {
     "title": "容器重启次数(按1小时)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"anyrobot\"}[1h]))",
       "legendFormat": "anyrobot"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\"}[1h]))",
       "legendFormat": "resource"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"kube-system\"}[1h]))",
       "legendFormat": "k8s组件"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace!~\"kube-system|anyrobot|resource\"}[1h]))",
       "legendFormat": "其他"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info)- sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
       "legendFormat": "总数"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_unavailable)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas) - sum(kube_statefulset_status_replicas_ready)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_unavailable)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_available)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_pod_status_phase{phase=~\"Running\",namespace=\"kube-system\", pod=~\"etcd.*|kube-apiserver.*|kube-controller-manager.*|kube-proxy.*|kube-scheduler.*\"} == 0)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_pod_status_phase{phase=~\"Running\",namespace=\"kube-system\", pod=~\"etcd.*|kube-apiserver.*|kube-controller-manager.*|kube-proxy.*|kube-scheduler.*\"} == 1)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "核心命名空间Pods健康度监控概览",
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {}
     ]
    },
    {
     "title": "核心业务容器运行状态",
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {}
     ]
    },
    {
     "title": "【Anyrobot】命名空间",
     "type": "grafana-polystat-panel",
     "description": "绿色: Running、Succeeded\n\n黄色：Pending\n\n红色：Unkown、Failed",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "(kube_pod_status_phase{namespace=\"anyrobot\",phase=\"Running\"} or kube_pod_status_phase{namespace=\"anyrobot\",phase=\"Succeeded\"}*2 or kube_pod_status_phase{namespace=\"anyrobot\",phase=\"Pending\"}*3 or kube_pod_status_phase{namespace=\"anyrobot\",phase=\"Unknown\"}*4 or kube_pod_status_phase{namespace=\"anyrobot\",phase=\"Failed\"}*5 )>0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "【Resource】命名空间",
     "type": "grafana-polystat-panel",
     "description": "绿色: Running、Succeeded\n\n黄色：Pending\n\n红色：Unkown、Failed",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 21 },
     "targets": [
      {
       "expr": "(kube_pod_status_phase{namespace=\"resource\",phase=\"Running\"} or kube_pod_status_phase{namespace=\"resource\",phase=\"Succeeded\"}*2 or kube_pod_status_phase{namespace=\"resource\",phase=\"Pending\"}*3 or kube_pod_status_phase{namespace=\"resource\",phase=\"Unknown\"}*4 or kube_pod_status_phase{namespace=\"resource\",phase=\"Failed\"}*5 )>0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "【kube-system】命名空间",
     "type": "grafana-polystat-panel",
     "description": "绿色: Running、Succeeded\n\n黄色：Pending\n\n红色：Unkown、Failed",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "(kube_pod_status_phase{namespace=\"kube-system\",phase=\"Running\"} or kube_pod_status_phase{namespace=\"kube-system\",phase=\"Succeeded\"}*2 or kube_pod_status_phase{namespace=\"kube-system\",phase=\"Pending\"}*3 or kube_pod_status_phase{namespace=\"kube-system\",phase=\"Unknown\"}*4 or kube_pod_status_phase{namespace=\"kube-system\",phase=\"Failed\"}*5 )>0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Opensearch-master",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 21 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Opensearch-hot",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 16, "y": 21 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Opensearch-warm",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 20, "y": 21 },
     "targets": [
      {}
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{statefulset=\"opensearch-master\"})by(namespace,statefulset) - sum(kube_statefulset_status_replicas_ready{statefulset=\"opensearch-master\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"opensearch-master\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{statefulset=\"opensearch-hot\"})by(namespace,statefulset) - sum(kube_statefulset_status_replicas_ready{statefulset=\"opensearch-hot\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"opensearch-hot\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{statefulset=\"opensearch-warm\"})by(namespace,statefulset) - sum(kube_statefulset_status_replicas_ready{statefulset=\"opensearch-warm\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"opensearch-warm\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\", pod=~\"opensearch-master.*\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\", pod=~\"opensearch-warm.*\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\", pod=~\"opensearch-warm\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    {
     "title": "当前时间段内Pod重启次数排行(Top20)",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(20,sum(increase(kube_pod_container_status_restarts_total[$__range]))by(pod,namespace))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ETCD",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 30 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Kafka",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 16, "y": 30 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Zookeeper",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 20, "y": 30 },
     "targets": [
      {}
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{statefulset=\"proton-etcd\"})by(namespace,statefulset) - sum(kube_statefulset_status_replicas_ready{statefulset=\"proton-etcd\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"proton-etcd\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{statefulset=\"kafka\"})by(namespace,statefulset) - sum(kube_statefulset_status_replicas_ready{statefulset=\"kafka\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"kafka\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{statefulset=\"zookeeper\"})by(namespace,statefulset) - sum(kube_statefulset_status_replicas_ready{statefulset=\"zookeeper\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"zookeeper\"})by(namespace,statefulset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{statefulset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\", pod=~\"proton-etcd.*\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\", pod=~\"kafka-[0-9]\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"resource\", pod=~\"zookeeper-[0-9]\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    {
     "title": "Logstash-input",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 39 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Logstash-filter",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 16, "y": 39 },
     "targets": [
      {}
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_unavailable{daemonset=\"logstash-input\"})by(namespace,daemonset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{daemonset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_available{daemonset=\"logstash-input\"})by(namespace,daemonset)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{daemonset}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"logstash-filter\"})by(namespace,deployment)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{deployment}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"logstash-filter\"})by(namespace,deployment)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "{{deployment}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"anyrobot\", pod=~\"opensearch-hot.*\"}[1h]))",
       "legendFormat": "容器重启次数"
      }
     ]
    },
    { "title": "容器重启次数(1小时内)", "type": "timeseries", "gridPos": { "h": 5, "w": 4, "x": 16, "y": 43 }, "fieldConfig": { "defaults": { "unit": "short" } } }
   ]
  }
 ]
}