{
 "title": "B-01_主机监控",
 "tags": [
  "product",
  "node",
  "node_exporter",
  "prometheus",
  "anyrobot",
  "monitor",
  "host"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "主机名",
    "query": {
     "query": "label_values(node_boot_time_seconds, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "系统运行时间",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{node=~\"$node\", mode='system'}) by (cpu, node))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "系统负载对比(5分钟)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{node=~\"$node\"}/on(node) count(node_cpu_seconds_total{node=~\"$node\", mode='system'}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU使用率对比",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}[10m]))by (node) * 100) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "已使用内存",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} - on(node) node_memory_MemAvailable_bytes{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "内存|CPU|负载【$node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存信息",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}",
       "legendFormat": "{{node}}_总内存"
      },
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"}",
       "legendFormat": "{{node}}_已用"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$node\"}",
       "legendFormat": "{{node}}_Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$node\"}",
       "legendFormat": "{{node}}_Cached"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{node=~\"$node\"}",
       "legendFormat": "{{node}}_可用"
      }
     ]
    },
    {
     "title": "CPU信息",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{node=~\"$node\",mode=\"system\"}[5m]))by(node)",
       "legendFormat": "{{node}}-System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{node=~\"$node\",mode=\"user\"}[5m]))by(node)",
       "legendFormat": "{{node}}-User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{node=~\"$node\",mode=\"idle\"}[5m]))by(node)",
       "legendFormat": "{{node}}-Idle"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{node=~\"$node\",mode=\"iowait\"}[5m]))by(node)",
       "legendFormat": "{{node}}-Iowait"
      }
     ]
    },
    {
     "title": "系统负载",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{node=~\"$node\"}/on(node) count(node_cpu_seconds_total{node=~\"$node\",mode='system'}) by (node)",
       "legendFormat": "{{node}}-1m"
      },
      {
       "expr": "node_load5{node=~\"$node\"}/on(node) count(node_cpu_seconds_total{node=~\"$node\",mode='system'}) by (node)",
       "legendFormat": "{{node}}-5m"
      },
      {
       "expr": "node_load15{node=~\"$node\"}/on(node) count(node_cpu_seconds_total{node=~\"$node\",mode='system'}) by (node)",
       "legendFormat": "{{node}}-15m"
      }
     ]
    },
    {
     "title": "打开描述符数",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{node=~\"$node\"}",
       "legendFormat": "{{node}}-Current"
      },
      {
       "expr": "node_filefd_maximum{node=~\"$node\"}",
       "legendFormat": "{{node}}-Max"
      }
     ]
    }
   ]
  },
  {
   "title": "存储【$node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "磁盘读写容量速率(bytes/秒)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_写入"
      }
     ]
    },
    {
     "title": "各分区空间使用情况",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{node=~'$node',fstype=~\"ext.*|xfs\"})by(node,mountpoint,device)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{node=~'$node',fstype=~\"ext.*|xfs\"} - node_filesystem_avail_bytes {node=~'$node',fstype=~\"ext.*|xfs\"})by(node,mountpoint,device)"
      },
      {
       "expr": "(1-(node_filesystem_avail_bytes{node=~'$node',fstype=~\"ext.*|xfs\"} / node_filesystem_size_bytes{node=~'$node',fstype=~\"ext.*|xfs\"}))*100 - 0"
      }
     ]
    },
    {
     "title": "磁盘读写次数速率(IOPS)(次/秒)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_写入"
      }
     ]
    },
    {
     "title": "磁盘IO使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "网络【$node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{node=~'$node',device!~'tap.*|cali.*|lo.*|tunl.*|veth.*|br.*'}[5m])",
       "legendFormat": "{{node}}-{{device}}_流入"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{node=~'$node',device!~'tap.*|cali.*|lo.*|tunl.*|veth.*|br.*'}[5m])",
       "legendFormat": "{{node}}-{{device}}_流出"
      }
     ]
    },
    {
     "title": "TCP 连接情况",
     "type": "timeseries",
     "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{node=~'$node'}",
       "legendFormat": "{{node}}-ESTABLISHED"
      },
      {
       "expr": "node_sockstat_TCP_tw{node=~'$node'}",
       "legendFormat": "{{node}}-TCP_tw"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{node=~'$node'}[1m])",
       "legendFormat": "{{node}}-ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{node=~'$node'}[1m])",
       "legendFormat": "{{node}}-PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_alloc{node=~'$node'}",
       "legendFormat": "{{node}}-TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{node=~'$node'}",
       "legendFormat": "{{node}}-TCP_inuse"
      }
     ]
    }
   ]
  },
  {
   "title": "其他【$node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "硬件温度",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{node=~\"$node\"}",
       "legendFormat": "{{node}}-{{chip}} {{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}