{
 "title": "C-01_OpenSearch存储监控",
 "tags": [
  "product",
  "anyrobot",
  "monitor",
  "storage",
  "detail",
  "opensearch",
  "hot",
  "warm"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "opensearch_pod",
    "query": {
     "query": "label_values(opensearch_filesystem_data_size_bytes, name)"
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$opensearch_pod\"}, node)"
    }
   },
   {
    "name": "rootVar",
    "label": "系统盘",
    "query": "disabled,#OPENSEARCH_VARS_ROOT#"
   },
   { "name": "hotVar", "label": "热数据", "query": "disabled,#OPENSEARCH_VARS_HOT#" },
   {
    "name": "warmVar",
    "label": "温数据",
    "query": "disabled,#OPENSEARCH_VARS_WARM#"
   },
   { "name": "root", "query": "#OPENSEARCH_VARS_ROOT#" },
   { "name": "hot", "query": "#OPENSEARCH_VARS_HOT#" },
   { "name": "warm", "query": "#OPENSEARCH_VARS_WARM#" },
   { "name": "rootDev", "query": "dm-0" },
   { "name": "hotDev", "query": "dm-0" },
   { "name": "warmDev", "query": "dm-0" },
   {
    "name": "deviceVar",
    "label": "存储设备",
    "query": "#OPENSEARCH_VARS_ROOTDEV#|#OPENSEARCH_VARS_HOTDEV#|#OPENSEARCH_VARS_WARMDEV#,#OPENSEARCH_VARS_HOTDEV#,#OPENSEARCH_VARS_WARMDEV#,#OPENSEARCH_VARS_ROOTDEV#"
   },
   { "name": "disk_warning", "query": "#STORAGE_WARNING#" },
   { "name": "disk_critical", "query": "#STORAGE_CRITICAL#" }
  ]
 },
 "panels": [
  {
   "title": "说明",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "变量",
     "type": "text",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "> 使用仪表盘前，请先正确配置变量：\n\n| 变量名 | 当前值 | 描述 |\n| ---- | ---- | ----|\n| node | ${node} | OpenSearch存储节点 |\n| hotVar | disabled,${hot} | 热数据分区 |\n| warmVar | disabled,${warm} | 温数据分区 |\n| rootVar | disabled,${root} | 系统分区 |\n| deviceVar | ${rootDev}\\|${hotDev}\\|${warmDev} | 存储设备 |\n\n\n----\n【请根据服务器实际情况进行配置】"
     }
    }
   ]
  },
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "存储分区数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"})",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "总数",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "存储分区空间使用率监控告警",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 3, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "热数据节点分布",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node)-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "温数据节点分布",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node)-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "警告",
   "type": "stat",
   "description": "统计磁盘空间使用百分比超过$disk_warning%的分区数量",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count($disk_critical > (1 -node_filesystem_free_bytes{node=~\"$node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}) * 100 >= $disk_warning )",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "Warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "紧急",
   "type": "stat",
   "description": "统计磁盘空间使用百分比超过$disk_critical%的分区数量",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count((1 -node_filesystem_free_bytes{node=~\"$node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$root|$hot|$warm\",fstype=~\"ext.*|xfs\"}) * 100 >= $disk_critical )",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "Critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "数据区域概览",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1 -node_filesystem_free_bytes{node=~\"$node\",mountpoint=~\"$root\",fstype=~\"ext.*|xfs\"}/node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$root\",fstype=~\"ext.*|xfs\"}) * 100",
     "legendFormat": "{{ node }}-{{mountpoint}}-system"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{node=~\"$node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"} / node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"})) * 100",
     "legendFormat": "{{ node }}-{{mountpoint}}-opensearch-hot"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{node=~\"$node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"} / node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"})) * 100",
     "legendFormat": "{{ node }}-{{mountpoint}}-opensearch-warm"
    }
   ]
  },
  {
   "title": "热数据区(按节点统计)",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"})by(node) or sum(node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"})"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes {node=~\"$node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"})by(node) or sum(node_filesystem_avail_bytes {node=~\"$node\",mountpoint=~\"$hot\",fstype=~\"ext.*|xfs\"})"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node)-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node)) *100/(sum(node_filesystem_avail_bytes {node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node)+sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node)-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})by(node))) or ((sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})) *100/(sum(node_filesystem_avail_bytes {node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})+sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$hot\"})))"
    }
   ]
  },
  {
   "title": "温数据区(按节点统计)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"})by(node) or sum(node_filesystem_size_bytes{node=~\"$node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"})"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes {node=~\"$node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"})by(node) or sum(node_filesystem_avail_bytes {node=~\"$node\",mountpoint=~\"$warm\",fstype=~\"ext.*|xfs\"})"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node)-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node)) *100/(sum(node_filesystem_avail_bytes {node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node)+sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node)-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})by(node))) or ((sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})) *100/(sum(node_filesystem_avail_bytes {node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})+sum(node_filesystem_size_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})-sum(node_filesystem_free_bytes{node=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint =~\"$warm\"})))"
    }
   ]
  },
  {
   "title": "存储分区",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "各分区空间使用情况",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(label_replace(label_replace(label_replace(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}, \"es_area\", \"2\", \"mountpoint\",  \"$hotVar\"), \"es_area\", \"1\", \"mountpoint\",  \"$warmVar\"), \"es_area\", \"0\", \"mountpoint\",  \"$rootVar\"))by(node,es_area,mountpoint,device)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"})by(node,mountpoint,device)"
      },
      {
       "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"})))by(node,mountpoint,device)"
      }
     ]
    },
    {
     "title": "磁盘使用率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint =~\"$hotVar|$warmVar|$rootVar\",node=~\"$node\"}))",
       "legendFormat": "{{node}}-{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "存储设备",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "磁盘读写容量速率(bytes/秒)",
     "type": "timeseries",
     "description": "每个磁盘存储设备每秒读取或写入的比特数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_写入"
      }
     ]
    },
    {
     "title": "磁盘读写次数速率(IOPS)(次/秒)",
     "type": "timeseries",
     "description": "读取/写入: 每个磁盘存储设备每秒读/写完成次数\n\nIO:每个磁盘存储设备每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_写入"
      },
      {
       "expr": "node_disk_io_now{device=~\"$deviceVar\",node=~\"$node\"}",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    },
    {
     "title": "磁盘IO使用率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    },
    {
     "title": "每次磁盘I/O操作耗时(秒/次)",
     "type": "timeseries",
     "description": "每个磁盘存储设备在读/写操作花费的秒数",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(node_disk_read_time_seconds_total{device=~\"$deviceVar\",node=~\"$node\"}[5m]) / increase(node_disk_reads_completed_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_读取"
      },
      {
       "expr": "increase(node_disk_write_time_seconds_total{device=~\"$deviceVar\",node=~\"$node\"}[5m]) / increase(node_disk_writes_completed_total{device=~\"$deviceVar\",node=~\"$node\"}[5m])",
       "legendFormat": "{{node}}-{{device}}_写入"
      }
     ]
    }
   ]
  }
 ]
}