{
 "title": "D-01_K8S_节点容量监控",
 "tags": [
  "product",
  "kubernetes",
  "anyrobot",
  "monitor",
  "node",
  "resource",
  "summary"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "概览",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "节点数",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "核" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "总容量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node!='', resource=\"cpu\"})",
     "legendFormat": "请求数"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node!='', resource=\"cpu\"})",
     "legendFormat": "限制数"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"} and on (node) kube_node_status_condition{status=\"true\",condition=\"Ready\"}==1)*(1- avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "实际使用"
    }
   ]
  },
  {
   "title": "内存",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "总容量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node!='', resource=\"memory\"})",
     "legendFormat": "请求数"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node!='', resource=\"memory\"})",
     "legendFormat": "限制数"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)",
     "legendFormat": "实际使用"
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "timeseries",
   "description": "磁盘容量=根分区容量+数据分区容量",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_size_bytes{fstype=~\"ext.*\"})",
     "legendFormat": "总容量"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_size_bytes{fstype=~\"ext.*\"}) - sum(node_filesystem_free_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_free_bytes{fstype=~\"ext.*\"})",
     "legendFormat": "已使用"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"}) ",
     "legendFormat": "总容量"
    },
    {
     "expr": "sum(kube_pod_info{node!=\"\"})",
     "legendFormat": "已使用"
    }
   ]
  },
  {
   "title": "不可用数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(kube_node_info) - sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"})",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "不可用数",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(kube_node_info)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "总数",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "集群资源使用情况(按节点统计)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node!=\"\"})by(node)"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"pods\"}"
    },
    {
     "expr": "(sum(kube_pod_info{node!=\"\"})by(node)/on(node) kube_node_status_capacity{resource=\"pods\"})*100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "核" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node!='', resource=\"cpu\"})by(node)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node!='', resource=\"cpu\"})by(node)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)*on(node)(1- avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))by(node))",
     "legendFormat": "实际使用"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)",
     "legendFormat": "容量"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{node!='', resource=\"cpu\"})by(node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)) * 100",
     "legendFormat": "容量"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))by (node))*100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "table",
   "description": "磁盘容量=根分区容量+数据分区容量",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_size_bytes{fstype=~\"ext.*\"})by(node) - sum(node_filesystem_free_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_free_bytes{fstype=~\"ext.*\"})by(node)",
     "legendFormat": "已使用"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_size_bytes{fstype=~\"ext.*\"})by(node)",
     "legendFormat": "容量"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_size_bytes{fstype=~\"ext.*\"})by(node) - sum(node_filesystem_free_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_free_bytes{fstype=~\"ext.*\"})by(node))/sum(node_filesystem_size_bytes{fstype=\"xfs\",mountpoint=\"/\"} or node_filesystem_size_bytes{fstype=~\"ext.*\"})by(node))*100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "内存",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node!='', resource=\"memory\"})by(node)",
     "legendFormat": "{{node}}-request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node!='', resource=\"memory\"})by(node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)by(node)",
     "legendFormat": "{{node}}-实际使用"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})by(node)",
     "legendFormat": "{{node}}-容量"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{node!='', resource=\"memory\"})by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node))*100",
     "legendFormat": "{{node}}-请求使用率"
    },
    {
     "expr": "(sum(sum(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)by(node))by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node))*100",
     "legendFormat": "{{node}}-使用率"
    }
   ]
  }
 ]
}