{
 "title": "D-02_K8S_工作负载监控(按命名空间)",
 "tags": [
  "product",
  "anyrobot",
  "kubernetes",
  "monitor",
  "namespace",
  "summary"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "命名空间【$namespace】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "namespace",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "概览",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "title": "详情",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_deployment_created{namespace=\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "部署数",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_statefulset_created{namespace=\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "有状态应用数",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_daemonset_created{namespace=\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "守护进程集数",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "expr": "sum((kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"} + kube_daemonset_status_number_available{namespace=~\"$namespace\"}) or kube_statefulset_status_replicas{namespace=~\"$namespace\"} or kube_deployment_status_replicas{namespace=~\"$namespace\"})",
       "legendFormat": "副本数"
      },
      {
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"} or (kube_statefulset_status_replicas{namespace=~\"$namespace\"} - kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}) or (kube_deployment_status_replicas{namespace=~\"$namespace\"} - kube_deployment_status_replicas_available{namespace=~\"$namespace\"}))",
       "legendFormat": "异常副本数"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_pod_info{namespace=\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "pod数",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\",phase=~\"Pending|Failed|Unknown\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "异常Pod数",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})",
       "legendFormat": "CPU请求数"
      },
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",image!=\"\",container!=\"POD\"}[5m]))",
       "legendFormat": "CPU使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"})",
       "legendFormat": "内存请求数"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",image!=\"\",container!=\"POD\"})",
       "legendFormat": "内存使用数"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Pods重启次数"
      }
     ]
    },
    {
     "title": "容器重启次数(按1小时)",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 10, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1h]))"
      }
     ]
    },
    {
     "title": "当前时间段内Pod重启次数排行(Top5)",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(5,sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[$__range]))by(pod,namespace))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU使用排行(Top5)",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5,sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",image!=\"\", container!=\"POD\"}[5m]))by(pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "内存使用排行(Top5)",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum(container_memory_working_set_bytes{namespace=\"$namespace\",image!=\"\",container!=\"POD\"})by(pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU请求排行(Top5)",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 4, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5,sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by(pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "内存请求排行(Top5)",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"})by(pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "工作负载",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {}
     ]
    },
    {
     "title": "部署(Deployments)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {}
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count((kube_deployment_status_replicas_available{namespace=~\"$namespace\"} - kube_deployment_status_replicas{namespace=~\"$namespace\"}) < 0)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"} - kube_deployment_status_replicas_available{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "部署副本数详情列表",
     "type": "table",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 16 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})by(namespace,deployment)"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})by(namespace,deployment)"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})by(namespace,deployment)"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})by(namespace,deployment)"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count((kube_deployment_status_replicas_available{namespace=~\"$namespace\"} - kube_deployment_status_replicas{namespace=~\"$namespace\"}) >= 0)",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "总数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_deployment_created{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "有状态应用(Statefulset)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {}
     ]
    },
    {
     "title": "不可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count((kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"} == 0) and (kube_statefulset_status_replicas{namespace=~\"$namespace\"} > 0))",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$namespace\"} - kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "有状态应用副本数详情列表",
     "type": "table",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 26 },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$namespace\"})by(namespace,statefulset)"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})by(namespace,statefulset)"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$namespace\"} - kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})by(namespace,statefulset)"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_updated{namespace=~\"$namespace\"})by(namespace,statefulset)"
      }
     ]
    },
    {
     "title": "可用数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count((kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"} > 0) or (kube_statefulset_status_replicas{namespace=~\"$namespace\"} == 0))",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "总数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_statefulset_created{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "守护进程集(Daemonsets)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {}
     ]
    },
    {
     "title": "不可用数(副本)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "守护进程集副本数详情列表",
     "type": "table",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 36 },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$namespace\"} + kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"})by(namespace,daemonset)"
      },
      {
       "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$namespace\"})by(namespace,daemonset)"
      },
      {
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"})by(namespace,daemonset)"
      }
     ]
    },
    {
     "title": "可用数(副本)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "总数",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(kube_daemonset_created{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "应用",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"} + kube_daemonset_status_number_available{namespace=~\"$namespace\"})",
       "group": { "alias": "", "name": "Status Checks", "url": "" },
       "legendFormat": "副本",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}