{
 "title": "D-03_K8S_Pods监控",
 "tags": [
  "product",
  "kubernetes",
  "anyrobot",
  "monitor",
  "pods",
  "detail"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(kube_pod_info, node)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\",node=~\"$node\"},created_by_name)"
    }
   },
   { "name": "podvar", "query": ".*" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\",node=~\"$node\",created_by_name=~\"$workload.*\",pod=~\"$podvar-.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,node)"
    },
    {
     "expr": "time() - sum(kube_pod_created{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
     "legendFormat": "运行时长"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
     "legendFormat": "重启次数"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
     "legendFormat": "容器数"
    },
    {
     "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,phase))>0",
     "legendFormat": "状态"
    },
    {
     "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "副本状态"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "请求内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "限制内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "使用内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "请求CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "限制CPU"
    },
    {
     "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
     "legendFormat": "限制CPU"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__range]))by(pod)",
     "legendFormat": "重启次数(last)"
    }
   ]
  },
  {
   "title": "Pod【$pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "pod",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "运行时间",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - kube_pod_created{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "读取: {{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "写入: {{ device }}"
      }
     ]
    },
    {
     "title": "容器重启次数(1小时内)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1h]))",
       "legendFormat": "重启次数"
      }
     ]
    },
    { "title": "Pod详情", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 0, "y": 16 } },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) ",
       "legendFormat": "使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\",resource=\"memory\"}) by(pod) ",
       "legendFormat": "限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) ",
       "legendFormat": "使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "限制数"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"}"
      },
      {
       "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,phase))>0"
      },
      {
       "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$pod\"})by(pod))"
      }
     ]
    },
    {
     "title": "容器",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"}"
      }
     ]
    }
   ]
  }
 ]
}