{
 "title": "D-04_K8S_容器监控",
 "tags": [
  "product",
  "kubernetes",
  "anyrobot",
  "monitor",
  "detail",
  "container"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "容器",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "容器【$container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "container",
   "targets": [
    {}
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m]) ))",
     "legendFormat": "流入"
    },
    {
     "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[5m]) ))",
     "legendFormat": "流出"
    }
   ]
  },
  {
   "title": "磁盘读写速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}[5m]))by(container,device) ",
     "legendFormat": "读取: {{ device }}"
    },
    {
     "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}[5m]))by(container,device) ",
     "legendFormat": "写入: {{ device }}"
    }
   ]
  },
  {
   "title": "容器重启次数(1小时内)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\",container=\"$container\"}[1h]))",
     "legendFormat": "重启次数"
    }
   ]
  },
  {
   "title": "容器详情",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\"}"
    },
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",pod=~\"$pod\"})by(pod,node)"
    }
   ]
  },
  {
   "title": "内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\",container=\"$container\"})by(pod,container) ",
     "legendFormat": "使用数"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\", resource=\"memory\"}) by(pod,container) ",
     "legendFormat": "请求数"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\", resource=\"memory\"}) by(pod,container) ",
     "legendFormat": "限制数"
    }
   ]
  },
  {
   "title": "CPU使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",image!=\"\",pod=~\"$pod\",container=\"$container\"}[5m])) by(pod,container) ",
     "legendFormat": "使用数"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\", resource=\"cpu\"}) by(pod,container) ",
     "legendFormat": "请求数"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\", resource=\"cpu\"}) by(pod,container) ",
     "legendFormat": "限制数"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\"} + kube_pod_container_status_waiting{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\"}*2 + kube_pod_container_status_terminated{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\"}*3)by(container,pod)"
    }
   ]
  }
 ]
}