{
 "title": "D-07_K8S_CoreDNS监控",
 "description": "A dashboard for the CoreDNS DNS server.",
 "tags": [
  "product",
  "coredns",
  "anyrobot",
  "monitor",
  "kubernetes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(coredns_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(coredns_build_info)", "legendFormat": "点击查看Pods" }
   ]
  },
  {
   "title": "请求数(按协议)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "请求数 (按类型)",
   "type": "timeseries",
   "description": "A记录：指向IPV4\n\nAAAA记录：指向IPV6\n\nCNAME记录：指向域名\n\nPTR记录：反向解析IP为域名",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "请求数 (按区域)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "响应数 (按响应码)",
   "type": "timeseries",
   "description": "NOERROR：查询请求成功完成\n\nFORMERR：查询请求格式错误\n\nSERVFAIL：服务端处理失败\n\nNXDOMAIN：请求查询的域名不存在\n\nNOTIMP：功能未实现\n\nREFUSED：服务端拒绝回复该查询",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "响应延迟",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le, job))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(coredns_dns_request_duration_milliseconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "响应流量",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}_P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(coredns_dns_response_size_bytes_bucket{instance=\"$instance\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}_P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}_P50"
    }
   ]
  },
  {
   "title": "请求流量",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\"}[10m])) by (le,proto))",
     "legendFormat": "{{proto}}_P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\"}[10m])) by (le,proto))",
     "legendFormat": "{{proto}}_P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}_P50"
    }
   ]
  },
  {
   "title": "缓存数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "缓存命中\\丢失率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "命中_{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "丢失"
    }
   ]
  }
 ]
}