{
 "title": "E-02_Logstash监控",
 "tags": [
  "monitor",
  "anyrobot",
  "app",
  "logstash",
  "product"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(logstash_events_in,namespace)"
    }
   },
   {
    "name": "anyrobot_module",
    "label": "服务",
    "query": {
     "query": "label_values(logstash_events_in{namespace=~\"$namespace\"}, anyrobot_module)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(logstash_events_in{anyrobot_module=~\"$anyrobot_module\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(logstash_events_duration_in_millis{anyrobot_module=~\"$anyrobot_module\"})",
     "legendFormat": "节点数"
    }
   ]
  },
  {
   "title": "当前日志速率(总计)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(logstash_events_in{anyrobot_module=~\"$anyrobot_module\"}[5m]))",
     "legendFormat": "接收"
    },
    {
     "expr": "sum(irate(logstash_events_filtered{anyrobot_module=~\"$anyrobot_module\"}[5m]))",
     "legendFormat": " 解析"
    },
    {
     "expr": "sum(irate(logstash_events_out{anyrobot_module=~\"$anyrobot_module\"}[5m]))",
     "legendFormat": " 输出"
    }
   ]
  },
  {
   "title": "管道事件持续时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(logstash_events_duration_in_millis{anyrobot_module=~\"$anyrobot_module\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "线程数(总计)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(logstash_jvm_threads_count{anyrobot_module=~\"$anyrobot_module\"})",
     "legendFormat": "线程数"
    },
    {
     "expr": "sum(logstash_jvm_threads_peak_count{anyrobot_module=~\"$anyrobot_module\"})",
     "legendFormat": "峰值线程数"
    },
    {
     "expr": "sum(logstash_hot_threads_busiest_threads{anyrobot_module=~\"$anyrobot_module\"})",
     "legendFormat": "热线程数"
    }
   ]
  },
  {
   "title": "当前打开文件描述符数(总计)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(logstash_process_open_file_descriptors{anyrobot_module=~\"$anyrobot_module\"})",
     "legendFormat": "当前打开文件描述符数"
    }
   ]
  },
  {
   "title": "管道",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "管道输入日志速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(logstash_events_in{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(logstash_events_in{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "管道输出日志速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(logstash_events_out{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(logstash_events_out{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "管道解析日志速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(logstash_events_filtered{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(logstash_events_filtered{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "管道持续时间",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "logstash_events_duration_in_millis{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "插件",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Inputs 输入\\输出速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(logstash_plugins_inputs_in{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}-{{plugin_id}}-输入"
      },
      {
       "expr": "irate(logstash_plugins_inputs_out{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}-{{plugin_id}}-输出"
      }
     ]
    },
    {
     "title": "Filters 日志输入\\输出速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(logstash_plugins_filters_in{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}-{{plugin_id}}-接收"
      },
      {
       "expr": "irate(logstash_plugins_filters_out{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}-{{plugin_id}}-输出"
      }
     ]
    },
    {
     "title": "Filters 持续时间",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "logstash_plugins_filters_duration_in_millis{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{plugin_id}}"
      }
     ]
    },
    {
     "title": "Outputs 输入\\输出速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(logstash_plugins_outputs_in{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}-{{plugin_id}}-输入"
      },
      {
       "expr": "irate(logstash_plugins_outputs_out{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}-{{plugin_id}}-输出"
      }
     ]
    },
    {
     "title": "Outputs 持续时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "logstash_plugins_outputs_duration_in_millis{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{plugin_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "系统",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "logstash_process_cpu_percent{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "虚拟内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "logstash_process_mem_total_virtual_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "打开文件描述符",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "logstash_process_max_file_descriptors{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-最大"
      },
      {
       "expr": "logstash_process_open_file_descriptors{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-当前"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC 次数（按小时）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(logstash_jvm_gc_collectors_collection_count{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[1h])",
       "legendFormat": "{{pod}}: {{generation}}"
      }
     ]
    },
    {
     "title": "GC 时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(logstash_jvm_gc_collectors_collection_time_in_millis{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}: {{generation}}"
      }
     ]
    },
    {
     "title": "线程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "logstash_jvm_threads_count{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "logstash_jvm_threads_peak_count{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: 峰值"
      }
     ]
    },
    {
     "title": "热线程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "logstash_hot_threads_busiest_threads{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "堆内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "logstash_jvm_mem_heap_used_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: 已使用"
      },
      {
       "expr": "logstash_jvm_mem_heap_committed_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: 已提交"
      }
     ]
    },
    {
     "title": "非堆内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "logstash_jvm_mem_non_heap_used_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "logstash_jvm_mem_non_heap_committed_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-committed"
      }
     ]
    },
    {
     "title": "堆使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "logstash_jvm_mem_heap_used_percent{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "缓存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "logstash_jvm_mem_pools_used_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{generation}}: 已使用"
      },
      {
       "expr": "logstash_jvm_mem_pools_committed_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{generation}}: 已提交"
      },
      {
       "expr": "logstash_jvm_mem_pools_max_in_bytes{anyrobot_module=~\"$anyrobot_module\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{generation}}: 最大"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}