{
 "title": "E-03_Kafka监控",
 "tags": [
  "monitor",
  "anyrobot",
  "app",
  "kafka",
  "product"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kafka_exporter_build_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "节点",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"kafka-[0-9]+\",namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "prometheus_ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "description": "描述集群的可用节点数及节点总数",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$namespace\"})",
     "legendFormat": "可用"
    },
    {
     "expr": "sum(kube_statefulset_replicas{statefulset=~\"kafka.*\",namespace=\"$namespace\"})",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "当前队列增长消费速率(总计)",
   "type": "stat",
   "description": "描述集群当前队列的总增长速率和总消费速率",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{topic!~\"__.+\"}[5m]))",
     "legendFormat": "增长"
    },
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{topic!~\"__.+\", consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"}[5m]))",
     "legendFormat": "消费"
    }
   ]
  },
  {
   "title": "Topic离线分区 & 离线副本数",
   "type": "stat",
   "description": "描述集群当前topic离线分区数总和及离线副本数总和",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "离线分区"
    },
    {
     "expr": "sum(kafka_server_replicamanager_offlinereplicacount)",
     "legendFormat": "离线副本"
    }
   ]
  },
  {
   "title": "消费组堆积总数",
   "type": "stat",
   "description": "描述集群当前消费者组的堆积总数",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic!~\"__.+\", consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"})",
     "legendFormat": "堆积"
    }
   ]
  },
  {
   "title": "Topic分区数Top5",
   "type": "grafana-polystat-panel",
   "description": "按topic中的分区数排序，展示前五位",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,kafka_topic_partitions{topic!~\"__.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "活跃控制器数",
   "type": "stat",
   "description": "描述集群当前活跃控制器总数",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)",
     "legendFormat": "活跃控制器数"
    }
   ]
  },
  {
   "title": "未同步副本数",
   "type": "stat",
   "description": "描述集群当前未同步副本总数",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas)-sum(kafka_topic_partition_in_sync_replica)",
     "legendFormat": "未同步副本数"
    }
   ]
  },
  {
   "title": "消费组成员数Top5",
   "type": "grafana-polystat-panel",
   "description": "按消费者组中的消费者个数排序，展示前五位",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,kafka_consumergroup_members{consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"})",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "请求队列空闲率",
   "type": "stat",
   "description": "描述集群当前所有节点请求队列空闲率的最小值",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent)*100",
     "legendFormat": "请求队列空闲率"
    }
   ]
  },
  {
   "title": "网络空闲率",
   "type": "stat",
   "description": "描述集群当前所有节点网络空闲率的最小值",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(kafka_network_socketserver_networkprocessoravgidlepercent)*100",
     "legendFormat": "网络空闲率"
    }
   ]
  },
  {
   "title": "Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "未同步副本数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "活跃控制器数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "离线副本数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_offlinereplicacount{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "离线分区数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "网络空闲率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "请求队列空闲率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic & 消费组",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Topic位移增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_topic_partition_current_offset{topic!~\"__.+\"}[5m]))by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "消费组堆积数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic!~\"__.+\", consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"})by(consumergroup)",
       "legendFormat": "{{consumergroup}}"
      }
     ]
    },
    {
     "title": "Topic-消费组消费速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(kafka_consumergroup_current_offset_sum{topic!~\"__.+\", consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"}[5m])",
       "legendFormat": "{{topic}}: {{consumergroup}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic分区 & 消费组",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Topic分区位移增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(kafka_topic_partition_current_offset{topic!~\"__.+\"}[5m])",
       "legendFormat": "{{topic}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Topic分区概览",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
     "targets": [
      {
       "expr": "label_join(kafka_topic_partition_replicas{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "副本数"
      },
      {
       "expr": "label_join(kafka_topic_partition_leader{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "Leader"
      },
      {
       "expr": "label_join(kafka_topic_partition_under_replicated_partition{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "是否有副本"
      },
      {
       "expr": "label_join(kafka_topic_partition_oldest_offset{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "最早位移"
      },
      {
       "expr": "label_join(kafka_topic_partition_current_offset{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "当前位移"
      },
      {
       "expr": "label_join(kafka_topic_partition_leader_is_preferred{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "Leader最优"
      },
      {
       "expr": "label_join(kafka_log_log_size{topic!~\"__.+\"},\"topic_p\",\"-\",\"topic\",\"partition\")",
       "legendFormat": "分区大小"
      }
     ]
    },
    {
     "title": "Topic分区-消费组堆积数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_consumergroup_lag{topic!~\"__.+\", consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"}",
       "legendFormat": "{{topic}}-{{partition}}:{{consumergroup}}"
      }
     ]
    },
    {
     "title": "Topic分区-消费组消费速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(kafka_consumergroup_current_offset{topic!~\"__.+\", consumergroup!~\"(anyrobot_data-replicator.+)|(.+.ar.dr.+)\"}[5m])",
       "legendFormat": "{{topic}}-{{partition}}:{{consumergroup}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM & 系统",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC 速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "GC 耗时增长率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "Full GC次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\",gc=\"G1 Old Generation\"})by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "GC平均耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "堆内存(已使用、已提交)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod)",
       "legendFormat": "{{pod}}: 已使用"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod)",
       "legendFormat": "{{pod}}: 已提交"
      }
     ]
    },
    {
     "title": "非堆内存(已使用、已提交)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\"$pod\",area=\"nonheap\"})by(pod)",
       "legendFormat": "{{pod}}: 已使用"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{namespace=~\"$namespace\", pod=~\"$pod\",area=\"nonheap\"})by(pod)",
       "legendFormat": "{{pod}}: 已提交"
      }
     ]
    },
    {
     "title": "堆使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(sum(jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod)/sum(jvm_memory_bytes_max{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "打开文件描述符数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(process_open_fds{namespace=\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-当前数"
      },
      {
       "expr": "sum(process_max_fds{namespace=\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-最大数"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m]))by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"})by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"})by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pod列表",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,node,pod_ip)"
      },
      {
       "expr": "time() - sum(kube_pod_created{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "运行时长"
      },
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "重启次数"
      },
      {
       "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "容器数"
      },
      {
       "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,phase))>0",
       "legendFormat": "状态"
      },
      {
       "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "副本状态"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "请求内存"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "限制内存"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "使用内存"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "请求CPU"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "限制CPU"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "限制CPU"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__range]))by(pod)",
       "legendFormat": "重启次数(当前字段)"
      }
     ]
    }
   ]
  }
 ]
}