{
 "title": "E-04_Etcd监控",
 "tags": [
  "product",
  "anyrobot",
  "monitor",
  "etcd",
  "app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "集群", "query": "proton-etcd" },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(etcd_server_version{job=\"$job\"},  namespace)"
    }
   },
   {
    "name": "pod",
    "label": "节点",
    "query": {
     "query": "label_values(etcd_server_version{job=\"$job\",  namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "当前Leader",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "etcd_server_is_leader{job=\"$job\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"$job\"})",
     "legendFormat": "可用数"
    },
    {
     "expr": "count(etcd_server_has_leader{job=\"$job\"})",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "当前所选时间段Leader选举次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "次" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(increase(etcd_server_leader_changes_seen_total{job=\"$job\"}[$__range]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "当前Keys数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(etcd_debugging_mvcc_keys_total{job=\"$job\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "当前活跃流数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=\"$job\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})- sum(grpc_server_handled_total{job=\"$job\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch 流"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"$job\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$job\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease 流"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"$job\",grpc_service=\"etcdserverpb.KV\",grpc_type=\"unary\"}) - sum(grpc_server_handled_total{job=\"$job\",grpc_service=\"etcdserverpb.KV\",grpc_type=\"unary\"})",
     "legendFormat": "KV 流"
    }
   ]
  },
  {
   "title": "详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Leader选举数(按小时统计)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(etcd_server_leader_changes_seen_total{job=\"$job\",pod=~\"$pod\"}[1h]))by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "磁盘同步持续时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"$job\",pod=~\"$pod\"}[5m])) by (pod, le))",
       "legendFormat": "{{pod}}: 预写日志(WAL)同步"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"$job\",pod=~\"$pod\"}[5m])) by (pod, le))",
       "legendFormat": "{{pod}}: DB同步"
      }
     ]
    },
    {
     "title": "Keys数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(etcd_debugging_mvcc_keys_total{job=\"$job\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RPC 速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(grpc_server_started_total{job=\"$job\",grpc_type=\"unary\",pod=~\"$pod\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}: 成功"
      },
      {
       "expr": "sum(irate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code!=\"OK\",pod=~\"$pod\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}: 失败"
      }
     ]
    },
    {
     "title": "代理流量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(etcd_network_client_grpc_received_bytes_total{job=\"$job\",pod=~\"$pod\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sum(irate(etcd_network_client_grpc_sent_bytes_total{job=\"$job\",pod=~\"$pod\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "对等流量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(etcd_network_peer_received_bytes_total{job=\"$job\",pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sum(irate(etcd_network_peer_sent_bytes_total{job=\"$job\",pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "活跃流数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(grpc_server_started_total{job=\"$job\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})- sum(grpc_server_handled_total{job=\"$job\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Watch 流"
      },
      {
       "expr": "sum(grpc_server_started_total{job=\"$job\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$job\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Lease 流"
      },
      {
       "expr": "sum(grpc_server_started_total{job=\"$job\",grpc_service=\"etcdserverpb.KV\",grpc_type=\"unary\"}) - sum(grpc_server_handled_total{job=\"$job\",grpc_service=\"etcdserverpb.KV\",grpc_type=\"unary\"})",
       "legendFormat": "KV 流"
      }
     ]
    },
    {
     "title": "Raft Proposals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(etcd_server_proposals_failed_total{job=\"$job\"}[5m]))",
       "legendFormat": "Proposal Failure Rate"
      },
      {
       "expr": "sum(etcd_server_proposals_pending{job=\"$job\"})",
       "legendFormat": "Proposal Pending Total"
      },
      {
       "expr": "sum(irate(etcd_server_proposals_committed_total{job=\"$job\"}[5m]))",
       "legendFormat": "Proposal Commit Rate"
      },
      {
       "expr": "sum(irate(etcd_server_proposals_applied_total{job=\"$job\"}[5m]))",
       "legendFormat": "Apply Rate"
      }
     ]
    },
    {
     "title": "DB 大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(etcd_mvcc_db_total_size_in_bytes{job=\"$job\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "驻留内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(process_resident_memory_bytes{job=\"$job\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}