{
 "title": "E-05_MariaDB监控",
 "tags": [
  "product",
  "anyrobot",
  "app",
  "monitor",
  "detail",
  "mysql"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(mysql_up,  namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(mysql_galera_variables_info, wsrep_cluster_name)"
    }
   },
   { "name": "name", "label": "节点", "query": { "query": "label_values(mysql_up,  name)" } }
  ]
 },
 "panels": [
  {
   "title": "总览【All】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "运行时长",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{namespace=~\"$namespace\", name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_queries{namespace=~\"$namespace\", name=~\"$name\"}[5m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_commands_total{namespace=~\"$namespace\", name=~\"$name\", command=~\"commit|rollback\"}[5m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_status_threads_connected{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "当前连接数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_variables_max_connections{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "连接限制数"
    }
   ]
  },
  {
   "title": "中断连接次数(当前时间区间内)",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(increase(mysql_global_status_aborted_connects{namespace=~\"$namespace\", name=~\"$name\"}[${__range_s}s]))",
     "legendFormat": "失败尝试次数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(increase(mysql_global_status_aborted_clients{namespace=~\"$namespace\", name=~\"$name\"}[${__range_s}s]))",
     "legendFormat": "客户端异常中断数"
    }
   ]
  },
  {
   "title": "慢查询数(当前时间段)",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(mysql_global_status_slow_queries{namespace=~\"$namespace\", name=~\"$name\"}[${__range_s}s]))",
     "legendFormat": "慢查询"
    }
   ]
  },
  {
   "title": "打开表数",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_status_open_tables{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "当前打开数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_variables_table_open_cache{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "限制数"
    }
   ]
  },
  {
   "title": "打开文件数",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_status_open_files{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "当前打开数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_variables_open_files_limit{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "限制数"
    }
   ]
  },
  {
   "title": "锁等待数",
   "type": "stat",
   "description": "当选择多个节点时，显示为累加值。",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(mysql_global_status_table_locks_waited{namespace=~\"$namespace\", name=~\"$name\"}[${__range_s}s]))",
     "legendFormat": "表锁等待数(当前时间段)"
    },
    {
     "expr": "sum(mysql_global_status_innodb_row_lock_current_waits{namespace=~\"$namespace\", name=~\"$name\"})",
     "legendFormat": "InnoDB行锁当前等待数"
    }
   ]
  },
  {
   "title": "QPS & TPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(mysql_global_status_queries{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(mysql_global_status_commands_total{namespace=~\"$namespace\",command=~\"commit|rollback\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "连接数 & 线程数 & 命令 & 处理器",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "连接数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_threads_connected{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}:  当前连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_max_used_connections{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}:  峰值连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "\nsum(mysql_global_variables_max_connections{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}:  连接限制数"
      }
     ]
    },
    {
     "title": "新增连接数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_connections{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "中断连接数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_aborted_connects{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 连接失败尝试次数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_aborted_clients{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 客户端异常中断数"
      }
     ]
    },
    {
     "title": "线程数",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_threads_running{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 运行数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_threads_cached{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 缓存数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_thread_cache_size{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 限制数"
      }
     ]
    },
    {
     "title": "命令执行数增长速率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_commands_total{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name,command)",
       "legendFormat": "{{name}}: 命令{{command}}"
      }
     ]
    },
    {
     "title": "非事务处理器数据增长率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_handlers_total{namespace=~\"$namespace\", name=~\"$name\",handler!~\"commit|rollback|savepoint.*|prepare\"}[5m]))by(name,handler)",
       "legendFormat": "{{name}}: {{handler}}"
      }
     ]
    },
    {
     "title": "事务处理器数据增长率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,sum(irate(mysql_global_status_handlers_total{namespace=~\"$namespace\", name=~\"$name\",handler=~\"commit|rollback|savepoint.*|prepare\"}[5m]))by(name,handler))",
       "legendFormat": "{{name}}: {{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "InnoDB缓存池",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_innodb_buffer_pool_size{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 限制数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_innodb_page_size{namespace=~\"$namespace\", name=~\"$name\"} * on (name) mysql_global_status_buffer_pool_pages{namespace=~\"$namespace\", name=~\"$name\", state=\"data\"})by(name)",
       "legendFormat": "{{name}}: 使用数"
      }
     ]
    },
    {
     "title": "当前行级锁等待数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg(mysql_global_status_innodb_row_lock_current_waits{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "新增行级锁等待数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg(increase(mysql_global_status_innodb_row_lock_waits{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "打开数 & 临时资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "打开文件数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_open_files_limit{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 打开文件限制数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_open_files{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 当前打开文件数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_innodb_num_open_files{namespace=~\"$namespace\",name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: InnoDB打开文件数"
      }
     ]
    },
    {
     "title": "打开表数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_table_open_cache{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 打开表限制数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_open_tables{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 当前打开表数"
      }
     ]
    },
    {
     "title": "打开表结构定义文件数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_table_definition_cache{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 打开表结构定义文件限制数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_open_table_definitions{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 当前打开表结构定义文件数"
      }
     ]
    },
    {
     "title": "新增打开表数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_opened_tables{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 打开表数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_table_open_cache_hits{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 打开表缓存命中数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_table_open_cache_misses{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 打开表缓存丢失数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_table_open_cache_overflows{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 打开缓存丢失数(溢出导致)"
      }
     ]
    },
    {
     "title": "新增临时资源数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_created_tmp_tables{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 临时表"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_created_tmp_disk_tables{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 临时磁盘表"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_created_tmp_files{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 临时文件"
      }
     ]
    }
   ]
  },
  {
   "title": "排序 & 查询 & 锁",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "排序统计数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时。\n\n1.sort_scan和sort_range\n不管是order by还是group by(除了使用order by null的group by)，主要是三步：\n第一步: 通过where条件找到记录\n第二步: 排序\n第三步:按照拍好的顺序读取记录。\n\n如果第二步不被跳过，那么第三步中就会有sort_scan或者sort_range。\n如果第一步是select_scan，那么第三步是sort_scan。\n如果第一步是select_range，那么第三步是sort_range。\n但是sort_scan和sort_range功能上没有区别，都是将需要的记录按照顺序读出来，所以性能是一样的。\n\n2.sort_merge_passes\n共两步，MYSQL首先会尝试在内存中做排序，使用的内存大小由系统变量sort_buffer_size决定，如果它的大小不够把所有的记录都读到内存中，MySQL就会把每次在内存中排序的结果存到临时文件中，等MYSQL找到所有记录之后，再把临时文件中的记录做一次排序。这再次排序就会增加sort_merge_passes。实际上，MYSQL会用另一个临时文件来存再次排序的结果，所以通常看到sort_merge_passes增加的数值是见临时文件数的两倍，因为用到了临时文件，所以速度可能会比较慢，增肌sort_buffer_size会减少sort_merge_passes和创建临时文件的次数。但是盲目增加sort_buffer_size不一定提高速度.\n\n3.sort_row：\n代表在第二步中有多少记录被排序",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_sort_rows{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 排序行数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_sort_range{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 范围内排序"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_sort_merge_passes{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 排序合并数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_sort_scan{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 表扫描排序"
      }
     ]
    },
    {
     "title": "Select连接查询数增长速率(按查询类型)",
     "type": "timeseries",
     "description": "select_scan：首表全表扫描查询连接数。在explain中type会显示为All，原因是查询没有用索引。因为全表扫描一般比较慢，所以应该尽量避免。\n\nselect_full_join：关联表全表扫描查询连接数。和select_scan差不多，区别是select_full_join代表的是第二张以及之后的表。explain中的类型也是all，原因是表连接所用的字段上没有索引。它对性能有更为严重的影响，绝对要避免，所以用于连接的字段上一般都要加索引。\n\nselect_range：首表范围内查询连接数。需要从硬盘读表在一段范围内的行。在explain中显示为range，说明使用了索引查询记录在硬盘上的位置\n\nselect_range_check：比select_full_join好一点，和select_range差不多。区别是MySQL不能确定它是否能够使用一个范围来做连接，如果可以会使用范围，则使用范围连接；如果不可以仍会使用全表扫描。在explain中type也是all，但是extra会有range checked for each record(index map)的名。\n\nselect_full_range_join：关联表范围内查询连接数。和select_range_check类似。不管mysql能够使用范围查找。这时explain中的类型是range。这也是需要优化的。\n\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_select_scan{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}: 首表全表扫描查询连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_select_full_join{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}: 关联表全表扫描查询连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_select_range{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}: 范围内首表查询连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_select_range_check{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}: 范围内首表查询连接数(每行不检查索引)"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(irate(mysql_global_status_select_full_range_join{namespace=~\"$namespace\", name=~\"$name\"}[5m]))by(name)",
       "legendFormat": "{{name}}: 范围内关联表全表扫描查询连接数"
      }
     ]
    },
    {
     "title": "新增慢查询数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_slow_queries{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "锁表统计数(按小时)",
     "type": "timeseries",
     "description": "按整小时统计，所选时间范围需大于1小时",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_table_locks_immediate{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 立即获取锁次数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(increase(mysql_global_status_table_locks_waited{namespace=~\"$namespace\", name=~\"$name\"}[1h]))by(name)",
       "legendFormat": "{{name}}: 等待授予锁数"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$name\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$name\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$name\"}[5m])) by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$name\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$name\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$name\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$name\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "常用系统变量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "常用系统变量",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_max_connections{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": " 最大连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_max_user_connections{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "最大用户连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_max_connect_errors{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "最大错误连接数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_wait_timeout{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "超时等待时长"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_thread_cache_size{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "线程缓存大小"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_table_open_cache{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": " 表打开限制数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_key_buffer_size{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "索引缓存大小"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_innodb_buffer_pool_size{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "Innodb缓存池大小"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_innodb_log_buffer_size{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "Innodb日志缓存大小"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_open_files_limit{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "最大打开文件数"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_long_query_time{namespace=~\"$namespace\", name=~\"$name\"})by(name)",
       "legendFormat": "慢查询时间"
      }
     ]
    }
   ]
  }
 ]
}