{
 "title": "E-06_Zookeeper监控",
 "tags": [
  "anyrobot",
  "monitor",
  "app",
  "zookeeper",
  "product"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "命名空间", "query": { "query": "label_values(zk_up, namespace)" } },
   { "name": "pod", "label": "节点", "query": { "query": "label_values(zk_up, pod)" } },
   { "name": "prometheus_ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "description": "描述集群的可用节点数及节点总数",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(zk_up{namespace=\"$namespace\"} == 1)",
     "legendFormat": "可用"
    },
    {
     "expr": "sum(kube_statefulset_replicas{statefulset=~\"zookeeper.*\",namespace=\"$namespace\"})",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "znode数",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点中的最大值",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(zk_ephemerals_count{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "临时数"
    },
    {
     "expr": "max(zk_znode_count{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "活跃客户端数",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点的累加值",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zk_num_alive_connections{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "活跃客户端数"
    }
   ]
  },
  {
   "title": "排队请求数",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点的最大值",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(zk_outstanding_requests{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "排队请求数"
    }
   ]
  },
  {
   "title": "延迟数",
   "type": "stat",
   "description": "当选择多个节点时，分别统计选中节点中的最大值和平均值",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(zk_max_latency{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "最大"
    },
    {
     "expr": "avg(zk_avg_latency{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "平均"
    }
   ]
  },
  {
   "title": "数据包速率",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点的累加值",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(zk_packets_received{namespace=\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "接收"
    },
    {
     "expr": "sum(irate(zk_packets_sent{namespace=\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "检测器数",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点的最大值",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(zk_watch_count{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "检测器数"
    }
   ]
  },
  {
   "title": "挂起同步数",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点的最大值(正常情况下，这是leader节点才有的数据)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(zk_pending_syncs{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "挂起同步数"
    }
   ]
  },
  {
   "title": "节点列表",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(zk_server_leader{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)"
    },
    {
     "expr": "max(zk_version{namespace=\"$namespace\", pod=~\"$pod\"})by(pod,version)"
    },
    {
     "expr": "max(zk_uptime{namespace=\"$namespace\", pod=~\"$pod\"})by(pod,version)"
    }
   ]
  },
  {
   "title": "打开文件描述符数",
   "type": "stat",
   "description": "当选择多个节点时，统计选中节点的累加值",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zk_open_file_descriptor_count{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "当前数"
    },
    {
     "expr": "sum(zk_max_file_descriptor_count{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "最大数"
    }
   ]
  },
  {
   "title": "详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "活跃客户端数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "zk_num_alive_connections{namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "数据包速率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(zk_packets_received{namespace=\"$namespace\", pod=~\"$pod\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}-接收"
      },
      {
       "expr": "sum(irate(zk_packets_sent{namespace=\"$namespace\", pod=~\"$pod\"}[5m]))by(pod)",
       "legendFormat": "{{pod}}-发送"
      }
     ]
    },
    {
     "title": "最大延迟",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(zk_max_latency{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "平均延迟",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(zk_avg_latency{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "检测器数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zk_watch_count{namespace=\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "znode数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zk_znode_count{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-总数"
      },
      {
       "expr": "sum(zk_ephemerals_count{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-临时数"
      }
     ]
    },
    {
     "title": "打开文件描述符数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(zk_open_file_descriptor_count{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-当前数"
      },
      {
       "expr": "sum(zk_max_file_descriptor_count{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-最大数"
      }
     ]
    },
    {
     "title": "排队请求数",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zk_outstanding_requests{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "挂起同步数",
     "type": "timeseries",
     "description": "只有leader节点有这个指标，若出现“No data\"表明所选节点中不包含leader节点。",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zk_pending_syncs{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "数据大小(估计值)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zk_approximate_data_size{namespace=\"$namespace\", pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM & 系统",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC 速率",
     "type": "timeseries",
     "description": "在某种程度上，Copy GC等价于Young GC，MarkSweepCompact等价于Old GC。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "GC 耗时增长率",
     "type": "timeseries",
     "description": "在某种程度上，Copy GC等价于Young GC，MarkSweepCompact等价于Old GC。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "Full GC次数",
     "type": "timeseries",
     "description": "在某种程度上，Copy GC等价于Young GC，MarkSweepCompact等价于Old GC。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\",gc=\"MarkSweepCompact\"})by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "GC平均耗时",
     "type": "timeseries",
     "description": "在某种程度上，Copy GC等价于Young GC，MarkSweepCompact等价于Old GC。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))by(pod,gc)",
       "legendFormat": "{{pod}}: {{gc}}"
      }
     ]
    },
    {
     "title": "堆内存(已使用、已提交)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod)",
       "legendFormat": "{{pod}}: 已使用"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod)",
       "legendFormat": "{{pod}}: 已提交"
      }
     ]
    },
    {
     "title": "非堆内存(已使用、已提交)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\"$pod\",area=\"nonheap\"})by(pod)",
       "legendFormat": "{{pod}}: 已使用"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{namespace=~\"$namespace\", pod=~\"$pod\",area=\"nonheap\"})by(pod)",
       "legendFormat": "{{pod}}: 已提交"
      }
     ]
    },
    {
     "title": "堆使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(sum(jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod)/sum(jvm_memory_bytes_max{namespace=~\"$namespace\", pod=~\"$pod\",area=\"heap\"})by(pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "打开文件描述符数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(process_open_fds{namespace=\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-当前数"
      },
      {
       "expr": "sum(process_max_fds{namespace=\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "{{pod}}-最大数"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pod列表",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,node,pod_ip)"
      },
      {
       "expr": "time() - sum(kube_pod_created{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "运行时长"
      },
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "重启次数"
      },
      {
       "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod)",
       "legendFormat": "容器数"
      },
      {
       "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod,phase))>0",
       "legendFormat": "状态"
      },
      {
       "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "副本状态"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "请求内存"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "限制内存"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "使用内存"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "请求CPU"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "限制CPU"
      },
      {
       "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\"})by(pod))",
       "legendFormat": "限制CPU"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__range]))by(pod)",
       "legendFormat": "重启次数(当前字段)"
      }
     ]
    }
   ]
  }
 ]
}