{
 "title": "E-07_Nginx-ingress监控",
 "tags": [
  "anyrobot",
  "monitor",
  "app",
  "nginx",
  "product"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
    }
   },
   {
    "name": "controller_pod",
    "label": "实例",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{controller_namespace=~\"$namespace\"}, controller_pod) "
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$controller_pod\",namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "当前连接数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{controller_namespace=~\"$namespace\"})by(state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "配置Reload次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_success{controller_namespace=~\"$namespace\"}",
     "legendFormat": "{{controller_pod}}"
    }
   ]
  },
  {
   "title": "最近一次配置Reload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_config_last_reload_successful{controller_namespace=~\"$namespace\"}",
     "legendFormat": "{{controller_pod}}"
    }
   ]
  },
  {
   "title": "SSL证书有效期",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_ssl_expire_time_seconds{namespace=~\"$namespace\"} - time()",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "当前连接数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_nginx_process_connections{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\"})by(controller_pod,state)",
       "legendFormat": "{{controller_pod}}: {{state}}"
      }
     ]
    },
    {
     "title": "连接数增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max(irate(nginx_ingress_controller_nginx_process_connections_total{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\",state=~\"accepted\"}[5m]))by(controller_pod)",
       "legendFormat": "{{controller_pod}}: 已接受"
      },
      {
       "expr": "max(irate(nginx_ingress_controller_nginx_process_connections_total{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\",state=~\"handled\"}[5m]))by(controller_pod)",
       "legendFormat": "{{controller_pod}}: 已处理"
      }
     ]
    },
    {
     "title": "请求数增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max(irate(nginx_ingress_controller_nginx_process_requests_total{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\"}[5m]))by(controller_pod)",
       "legendFormat": "{{controller_pod}}"
      },
      {
       "expr": "max(irate(nginx_ingress_controller_nginx_process_write_bytes_total{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\"}[5m]))by(controller_pod)",
       "legendFormat": "{{controller_pod}}-写入"
      }
     ]
    },
    {
     "title": "进程数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(nginx_ingress_controller_nginx_process_num_procs{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\"})by(controller_pod)",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    },
    {
     "title": "虚拟内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(nginx_ingress_controller_nginx_process_virtual_memory_bytes{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\"})by(controller_pod)",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    },
    {
     "title": "驻留内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_namespace=\"$namespace\",controller_pod=~\"$controller_pod\"})by(controller_pod)",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$pod\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$pod\"}[5m])) by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{image!=\"\", pod=~\"$pod\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}