{
 "title": "E-08_日志数据流监控",
 "tags": [
  "product",
  "business",
  "anyrobot",
  "app",
  "monitor",
  "detail"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "命名空间", "query": "anyrobot" },
   {
    "name": "input_pod",
    "query": {
     "query": "label_values(logstash_events_in{namespace=~\"$namespace\",anyrobot_module=\"logstash-input\"}, pod)"
    }
   },
   {
    "name": "filter_pod",
    "query": {
     "query": "label_values(logstash_events_in{namespace=~\"$namespace\",anyrobot_module=\"logstash-filter\"}, pod)"
    }
   },
   {
    "name": "opensearch_pod",
    "query": {
     "query": "label_values(opensearch_indices_indexing_index_total {namespace=~\"resource\"}, name)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(kafka_topic_partition_replicas{namespace=~\"resource\",topic=\"kafka_topic\"}, partition)"
    }
   },
   {
    "name": "dir_monitor_pod",
    "query": {
     "query": "label_values(logstash_events_in{namespace=~\"$namespace\",anyrobot_module=\"dir-monitor\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "日志数据流监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "日志接收器",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "日志队列",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{namespace=~\"resource\",topic=\"kafka_topic\"}[5m]))",
     "legendFormat": "Kafka_生产速率"
    },
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"kafka_topic\"})",
     "legendFormat": "Kafka_堆积数"
    },
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"kafka_topic\"}[5m]))",
     "legendFormat": "Kafka_消费速率"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 12, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "日志解析器",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 18, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "日志存储库",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$input_pod",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "repeat": "input_pod",
   "targets": [
    {
     "expr": "sum(irate(logstash_events_in{namespace=~\"$namespace\",pod=\"$input_pod\"}[5m]))",
     "legendFormat": "Input_输入速率"
    },
    {
     "expr": "sum(irate(logstash_events_filtered{namespace=~\"$namespace\",pod=\"$input_pod\"}[5m]))",
     "legendFormat": "Input_处理速率"
    },
    {
     "expr": "sum(irate(logstash_events_out{namespace=~\"$namespace\",pod=\"$input_pod\"}[5m]))",
     "legendFormat": "Input_输出速率"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "repeat": "input_pod",
   "options": {
    "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-----></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "分区：$partition",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "repeat": "partition",
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{namespace=~\"resource\",topic=\"kafka_topic\",partition=~\"$partition\"}[5m]))",
     "legendFormat": "Kafka_生产速率"
    },
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"kafka_topic\",partition=~\"$partition\"})",
     "legendFormat": "Kafka_堆积数"
    },
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"kafka_topic\",partition=~\"$partition\"}[5m]))",
     "legendFormat": "Kafka_消费速率"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 2 },
   "repeat": "partition",
   "options": {
    "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-----></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$filter_pod",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 2 },
   "repeat": "filter_pod",
   "targets": [
    {
     "expr": "sum(irate(logstash_events_in{namespace=~\"$namespace\",pod=~\"$filter_pod\"}[5m]))",
     "legendFormat": "Filter_输入速率"
    },
    {
     "expr": "sum(irate(logstash_events_filted{namespace=~\"$namespace\",pod=~\"$filter_pod\"}[5m]))",
     "legendFormat": "Filter_处理速率"
    },
    {
     "expr": "sum(irate(logstash_events_out{namespace=~\"$namespace\",pod=~\"$filter_pod\"}[5m]))",
     "legendFormat": "Filter_输出速率"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 2 },
   "repeat": "filter_pod",
   "options": {
    "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-----></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$opensearch_pod",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "repeat": "es_node",
   "targets": [
    {
     "expr": "sum(irate(opensearch_indices_indexing_index_total{namespace=~\"resource\", name=~\"$opensearch_pod\"}[5m]))by(name)",
     "legendFormat": "Elasticsearch_索引速率"
    }
   ]
  },
  {
   "title": "归档数据流监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "日志接收器",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 4, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "title": "日志队列",
     "type": "text",
     "gridPos": { "h": 1, "w": 6, "x": 6, "y": 18 },
     "targets": [
      {
       "expr": "sum(irate(kafka_topic_partition_current_offset{namespace=~\"resource\",topic=\"kafka_topic\"}[5m]))",
       "legendFormat": "Kafka_生产速率"
      },
      {
       "expr": "sum(kafka_consumergroup_lag{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"kafka_topic\"})",
       "legendFormat": "Kafka_堆积数"
      },
      {
       "expr": "sum(irate(kafka_consumergroup_current_offset{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"kafka_topic\"}[5m]))",
       "legendFormat": "Kafka_消费速率"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 12, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "title": "日志归档器",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 14, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 2, "x": 18, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "title": "日志存储",
     "type": "text",
     "gridPos": { "h": 1, "w": 4, "x": 20, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "title": "$input_pod",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
     "repeat": "input_pod",
     "targets": [
      {
       "expr": "sum(irate(logstash_events_in{namespace=~\"$namespace\",pod=\"$input_pod\"}[5m]))",
       "legendFormat": "Input_输入速率"
      },
      {
       "expr": "sum(irate(logstash_events_filtered{namespace=~\"$namespace\",pod=\"$input_pod\"}[5m]))",
       "legendFormat": "Input_处理速率"
      },
      {
       "expr": "sum(irate(logstash_events_out{namespace=~\"$namespace\",pod=\"$input_pod\"}[5m]))",
       "legendFormat": "Input_输出速率"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 19 },
     "repeat": "input_pod",
     "options": {
      "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-----></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "分区：$partition",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "sum(irate(kafka_topic_partition_current_offset{namespace=~\"resource\",topic=\"kafka_topic\",partition=~\"$partition\"}[5m]))",
       "legendFormat": "Kafka_生产速率"
      },
      {
       "expr": "sum(kafka_consumergroup_lag{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"archive\",partition=~\"$partition\"})",
       "legendFormat": "Kafka_堆积数"
      },
      {
       "expr": "sum(irate(kafka_consumergroup_current_offset{namespace=~\"resource\",topic=\"kafka_topic\",consumergroup=\"archive\",partition=~\"$partition\"}[5m]))",
       "legendFormat": "Kafka_消费速率"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 19 },
     "repeat": "partition",
     "options": {
      "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-----></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "日志归档器",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 5, "w": 4, "x": 14, "y": 19 },
     "targets": [
      {
       "expr": "sum(irate(logstash_events_in{namespace=~\"$namespace\",pod=\"$dir_monitor_pod\"}[5m]))",
       "legendFormat": "Dir-monitor_输入速率"
      },
      {
       "expr": "sum(irate(logstash_events_filtered{namespace=~\"$namespace\",pod=\"$dir_monitor_pod\"}[5m]))",
       "legendFormat": "Dir-monitor_处理速率"
      },
      {
       "expr": "sum(irate(logstash_events_out{namespace=~\"$namespace\",pod=\"$dir_monitor_pod\"}[5m]))",
       "legendFormat": "Dir-monitor_输出速率"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 2, "x": 18, "y": 19 },
     "options": {
      "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-----></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
     "options": {
      "content": "\r\n<br />\r\n\t<br />\r\n\t<br />\r\n<p> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<<<存储服务器>>>></p>\r\n<br />\r\n\t<br />\r\n\t<br />\r\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}