# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - "feature-*"
      - "feature/*"
      - "develop"
      - "release-*"
      - "release/*"

variables:
  - group: anyrobot-global-config
  - name: IMAGE_REGISTRY
    value: "acr.aishu.cn"
  - name: IMAGE_REPOSITORY
    value: "proton/proton-grafana"
  - name: CHART_REPO
    value: "https://acr.aishu.cn/api/chartrepo/proton/charts"
  - name: CHART_NAME
    value: "proton-grafana"
  - name: IS_RELEASE
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release')]
  - name: YQ_IMAGE
    value: "acr.aishu.cn/public/mikefarah/yq:4.26.1"
  - name: BASE_IMAGE
    value: "acr.aishu.cn/public/grafana:10.4.19-security-01-ubuntu"
  - name: POLYSTAT_PANEL_PLUGIN_VERSION
    value: "2.1.14"
  - name: ANYROBOT_PLUGIN_VERSION
    value: "1.0.5"

parameters:
  - name: TRIVY_EXIT_CODE
    displayName: trivy exit code
    type: number
    default: 1
    values:
      - 0
      - 1

resources:
  repositories:
    - repository: templatesAlias
      type: git
      name: ONE-Architecture\Yaml-Templates
      ref: "refs/heads/main"

stages:
  - stage: InitVariable
    displayName: 初始化版本号
    jobs:
      - job: InitVariable
        pool: anyrobot-pools
        workspace:
          clean: all
        steps:
          - checkout: self

          - bash: |
              set -ex

              CommitID="$(Build.SourceVersion)"
              CommitID="${CommitID:0:6}"

              version=`cat VERSION`
              current_tag="${version}-$(Build.SourceBranchName).$(Build.BuildNumber).${CommitID}"
              latest_tag="${version}-$(Build.SourceBranchName)"
              if [ $(IS_RELEASE) = True ]; then
                current_tag="${version}-$(Build.BuildNumber).${CommitID}"
                latest_tag="${version}"
              fi

              set +x
              echo "##vso[task.setvariable variable=CURRENT_TAG;isoutput=true]$current_tag"
              set +x
              echo "##vso[task.setvariable variable=LATEST_TAG;isoutput=true]$latest_tag"
            name: MyOutputVar

          - task: Post-Bash@3
            inputs:
              targetType: inline
              script: |
                rm -rf $(Build.SourcesDirectory)
                ls -lah $(Agent.BuildDirectory)

  - stage: BuildImage
    displayName: 镜像编译
    dependsOn:
      - InitVariable
    variables:
      CURRENT_TAG: $[stageDependencies.InitVariable.InitVariable.outputs['MyOutputVar.CURRENT_TAG']]
      LATEST_TAG: $[stageDependencies.InitVariable.InitVariable.outputs['MyOutputVar.LATEST_TAG']]
    jobs:
      - job: BuildImage
        displayName: 镜像编译
        workspace:
          clean: all
        strategy:
          matrix:
            amd64:
              ARCH_TYPE: amd64
              poolAgentOSArchitecture: X64
            arm64:
              ARCH_TYPE: arm64
              poolAgentOSArchitecture: ARM64
          maxParallel: 2
        pool:
          name: anyrobot-pools
          demands:
            - Agent.OSArchitecture -equals $(poolAgentOSArchitecture)
            - Agent.OS -equals Linux
            - docker
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 登录容器仓库
            inputs:
              containerRegistry: "ACRDockerRegistry"
              command: "login"

          - task: Bash@3
            name: BuildImageTask
            displayName: 编译镜像
            inputs:
              targetType: inline
              script: |
                #!/usr/bin/env bash
                set -ex

                IMAGE_NAME=$(IMAGE_REGISTRY)/$(IMAGE_REPOSITORY)-$(ARCH_TYPE)
                CURRENT_IMAGE=${IMAGE_NAME}:$(CURRENT_TAG)
                LATEST_IMAGE=${IMAGE_NAME}:$(LATEST_TAG)

                cd docker

                mkdir -p plugins
                wget https://ftp-ar.aishu.cn/Grafana/grafana-anyrobot-datasource-$(ANYROBOT_PLUGIN_VERSION).tar.gz -O plugins/grafana-anyrobot-datasource.tar.gz
                wget https://ftp-ar.aishu.cn/Grafana/grafana-anyrobot-metric-model-datasource-$(ANYROBOT_PLUGIN_VERSION).tar.gz -O plugins/grafana-anyrobot-metric-model-datasource.tar.gz
                wget https://ftp-ar.aishu.cn/Grafana/grafana-polystat-panel-$(POLYSTAT_PANEL_PLUGIN_VERSION).any.tar.gz -O plugins/grafana-polystat-panel.any.tar.gz
                ls -l plugins

                docker build --force-rm --no-cache --pull \
                  -t ${CURRENT_IMAGE} -f Dockerfile \
                  --build-arg BASE_IMAGE=$(BASE_IMAGE) .

                set +x
                echo "##vso[task.setvariable variable=CURRENT_IMAGE;isoutput=true]$CURRENT_IMAGE"
                set +x
                echo "##vso[task.setvariable variable=LATEST_IMAGE;isoutput=true]$LATEST_IMAGE"

          - template: scan-image-step.yml@templatesAlias
            parameters:
              imageName: $(BuildImageTask.CURRENT_IMAGE)
              exitCode: ${{ parameters.TRIVY_EXIT_CODE }}
              scanTimeout: 10m

          - task: Bash@3
            displayName: 推送镜像
            inputs:
              targetType: inline
              script: |
                #!/usr/bin/env bash
                set -ex
                docker tag $(BuildImageTask.CURRENT_IMAGE) $(BuildImageTask.LATEST_IMAGE)
                docker push $(BuildImageTask.CURRENT_IMAGE)
                docker push $(BuildImageTask.LATEST_IMAGE)
                docker rmi $(BuildImageTask.CURRENT_IMAGE) $(BuildImageTask.LATEST_IMAGE)

          - task: Post-Bash@3
            inputs:
              targetType: inline
              script: |
                docker ps -a -q -f status=exited | xargs -I {} docker rm {}
                docker images -q -f dangling=true | xargs -I {} docker rmi {}
                rm -rf $(Build.SourcesDirectory)
                ls -lah $(Agent.BuildDirectory)

  - stage: MakeManifest
    displayName: 制作多架构镜像
    dependsOn:
      - InitVariable
      - BuildImage
    variables:
      CURRENT_TAG: $[stageDependencies.InitVariable.InitVariable.outputs['MyOutputVar.CURRENT_TAG']]
      LATEST_TAG: $[stageDependencies.InitVariable.InitVariable.outputs['MyOutputVar.LATEST_TAG']]
    jobs:
      - job: MakeManifest
        displayName: 制作多架构镜像
        workspace:
          clean: all
        pool:
          name: anyrobot-pools
          demands:
            - Agent.OSArchitecture -equals X64
            - Agent.OS -equals Linux
            - docker
        steps:
          - task: Docker@2
            displayName: 登录容器仓库
            inputs:
              containerRegistry: ACRDockerRegistry
              command: login

          - task: Bash@3
            displayName: 制作多架构镜像
            inputs:
              targetType: inline
              script: |
                #!/usr/bin/env bash
                set -ex

                IMAGE_NAME="$(IMAGE_REGISTRY)/$(IMAGE_REPOSITORY)"

                docker manifest create --amend ${IMAGE_NAME}:$(CURRENT_TAG) ${IMAGE_NAME}-amd64:$(CURRENT_TAG) ${IMAGE_NAME}-arm64:$(CURRENT_TAG)
                docker manifest push -p ${IMAGE_NAME}:$(CURRENT_TAG)

                docker manifest create --amend ${IMAGE_NAME}:$(LATEST_TAG) ${IMAGE_NAME}-amd64:$(LATEST_TAG) ${IMAGE_NAME}-arm64:$(LATEST_TAG)
                docker manifest push -p ${IMAGE_NAME}:$(LATEST_TAG)

          - task: Post-Bash@3
            inputs:
              targetType: inline
              script: |
                rm -rf $(Build.SourcesDirectory)
                ls -lah $(Agent.BuildDirectory)

  - stage: ChartPush
    displayName: Chart构建
    dependsOn:
      - InitVariable
      - MakeManifest
    variables:
      CURRENT_TAG: $[stageDependencies.InitVariable.InitVariable.outputs['MyOutputVar.CURRENT_TAG']]
      LATEST_TAG: $[stageDependencies.InitVariable.InitVariable.outputs['MyOutputVar.LATEST_TAG']]
    jobs:
      - job: ChartPush
        displayName: Chart构建
        workspace:
          clean: all
        pool:
          name: anyrobot-pools
          demands:
            - Agent.OSArchitecture -equals X64
            - Agent.OS -equals Linux
            - docker
        steps:
          - checkout: self

          - task: Bash@3
            displayName: Chart构建
            inputs:
              targetType: inline
              script: |
                #!/usr/bin/env
                set -ex

                chmod 777 -R $(pwd)/helm
                docker run --rm \
                      -v $(pwd)/helm:/chart \
                      --entrypoint='' \
                      $(YQ_IMAGE) sh -c "
                  set -ex

                  yq eval -i '.image.registry = \"$(IMAGE_REGISTRY)\"' /chart/proton-grafana/values.yaml
                  yq eval -i '.image.grafana.repository = \"$(IMAGE_REPOSITORY)\"' /chart/proton-grafana/values.yaml
                  yq eval -i '.image.grafana.tag = \"$(CURRENT_TAG)\"' /chart/proton-grafana/values.yaml

                  yq eval -i '.appVersion = \"$(CURRENT_TAG)\"' /chart/proton-grafana/Chart.yaml

                  yq eval -i '.version = \"$(CURRENT_TAG)\"' /chart/proton-grafana/Chart.yaml
                  cd /chart && tar -czf $(CHART_NAME)-$(CURRENT_TAG).tar.gz proton-grafana

                  yq eval -i '.version = \"$(LATEST_TAG)\"' /chart/proton-grafana/Chart.yaml
                  cd /chart && tar -czf $(CHART_NAME)-$(LATEST_TAG).tar.gz proton-grafana
                  "

                cd helm
                curlOptions="-s -u $(registry.username):$(registry.password) -H \"Content-Type:multipart/form-data\""
                curl ${curlOptions} -F "chart=@$(CHART_NAME)-$(CURRENT_TAG).tar.gz;type=application/x-compressed-tar" -X POST "$(CHART_REPO)"
                curl ${curlOptions} -F "chart=@$(CHART_NAME)-$(LATEST_TAG).tar.gz;type=application/x-compressed-tar" -X POST "$(CHART_REPO)"

          - task: Post-Bash@3
            inputs:
              targetType: inline
              script: |
                rm -rf $(Build.SourcesDirectory)
                ls -lah $(Agent.BuildDirectory)
