# Prometheus configuration format https://prometheus.io/docs/prometheus/latest/configuration/configuration/
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus.name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "prometheus.name" . }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.prometheus.scrape_interval }}
      scrape_timeout: {{ .Values.config.prometheus.scrape_timeout }}


    rule_files:
      - /etc/config/rules/*.rules


    scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets:
          - {{ .Release.Name }}:9090


      # API Serevrs
      - job_name: kubernetes-apiservers
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            regex: default;kubernetes;https


      # node(kubelet)
      - job_name: kubernetes-nodes
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)


      # Kubelet cAdvisor
      - job_name: kubernetes-cadvisor
        scheme: https
        metrics_path: /metrics/cadvisor
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)


      # service endpoints
      - job_name: kubernetes-services-endpoints
        honor_labels: true
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            regex: true
          - action: drop
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
            regex: true
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            regex: (https?)
            target_label: __scheme__
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: replace
            source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod


      # service endpoints slow
      - job_name: kubernetes-services-endpoints-slow
        honor_labels: true
        scrape_interval: {{ .Values.config.prometheus.scrape_slow_interval }}
        scrape_timeout: {{ .Values.config.prometheus.scrape_slow_timeout }}
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
            regex: true
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            regex: (https?)
            target_label: __scheme__
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: replace
            source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod


      # # probing services via the Blackbox Exporter.
      # - job_name: kubernetes-services
      #   honor_labels: true
      #   metrics_path: /probe
      #   params:
      #     module: [http_2xx]
      #   kubernetes_sd_configs:
      #     - role: service
      #   relabel_configs:
      #     - action: keep
      #       source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probed]
      #       regex: true
      #     - action: replace
      #       source_labels: [__address__]
      #       target_label: __param_target
      #     - action: replace
      #       target_label: __address__
      #       replacement: blackbox
      #     - action: replace
      #       source_labels: [__param_target]
      #       target_label: instance
      #     - action: labelmap
      #       regex: __meta_kubernetes_service_label_(.+)
      #     - action: replace
      #       source_labels: [__meta_kubernetes_namespace]
      #       target_label: namespace
      #     - action: replace
      #       source_labels: [__meta_kubernetes_service_name]
      #       target_label: service


      # # probing ingresses via the Blackbox Exporter.
      # - job_name: kubernetes-ingresses
      #   honor_labels: true
      #   metrics_path: /probe
      #   params:
      #     module: [http_2xx]
      #   kubernetes_sd_configs:
      #     - role: ingress
      #   relabel_configs:
      #     - action: keep
      #       source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probed]
      #       regex: true
      #     - action: replace
      #       source_labels:
      #         - __meta_kubernetes_ingress_scheme
      #         - __address__
      #         - __meta_kubernetes_ingress_path
      #       regex: (.+);(.+);(.+)
      #       target_label: __param_target
      #       replacement: ${1}://${2}${3}
      #     - action: replace
      #       target_label: __address__
      #       replacement: blackbox-exporter.example.com:9115
      #     - action: replace
      #       source_labels: [__param_target]
      #       target_label: instance
      #     - action: labelmap
      #       regex: __meta_kubernetes_ingress_label_(.+)
      #     - action: replace
      #       source_labels: [__meta_kubernetes_namespace]
      #       target_label: namespace
      #     - action: replace
      #       source_labels: [__meta_kubernetes_ingress_name]
      #       target_label: ingress


      #pods
      - job_name: kubernetes-pods
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: true
          - action: drop
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
            regex: true
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            regex: (https?)
            target_label: __scheme__
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: replace
            source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: drop
            source_labels: [__meta_kubernetes_pod_phase]
            regex: Pending|Succeeded|Failed|Completed


      # pods slow
      - job_name: kubernetes-pods-slow
        honor_labels: true
        scrape_interval: {{ .Values.config.prometheus.scrape_slow_interval }}
        scrape_timeout: {{ .Values.config.prometheus.scrape_slow_timeout }}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
            regex: true
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            regex: (https?)
            target_label: __scheme__
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: replace
            source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: drop
            source_labels: [__meta_kubernetes_pod_phase]
            regex: Pending|Succeeded|Failed|Completed


{{ if .Values.secret.k8sEtcd.enabled }}
      - job_name: kubernetes-etcd
        scheme: https
        tls_config:
          ca_file: /etc/ssl/k8s-etcd/{{ .Values.secret.k8sEtcd.caName }}
          cert_file: /etc/ssl/k8s-etcd/{{ .Values.secret.k8sEtcd.certName }}
          key_file: /etc/ssl/k8s-etcd/{{ .Values.secret.k8sEtcd.keyName }}
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels: [__address__]
            target_label: __address__
            replacement: $1:2379
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: kube-system
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_component]
            regex: etcd
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
{{ end }}


{{ if .Values.secret.protonEtcd.enabled }}
      - job_name: proton-etcd
        scheme: https
        tls_config:
          ca_file: /etc/ssl/proton-etcd/{{ .Values.secret.protonEtcd.caName }}
          cert_file: /etc/ssl/proton-etcd/{{ .Values.secret.protonEtcd.certName }}
          key_file: /etc/ssl/proton-etcd/{{ .Values.secret.protonEtcd.keyName }}
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels: [__address__]
            target_label: __address__
            regex: ([^:]+)(?::\d+)?
            replacement: $1:2379
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: resource
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: proton-etcd
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
{{ end }}


{{- if .Values.config.prometheus.alertmanager }}
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_namespace]
          regex: {{ .Values.namespace }}
        - action: keep
          source_labels: [__meta_kubernetes_pod_label_k8s_app]
          regex: alertmanager
        - action: drop
          source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
{{- end -}}
