apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "prometheus.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prometheus.name" . }}
  labels:
    app: {{ template "prometheus.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
      - "/metrics/cadvisor"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheus.name" . }}
  labels:
    app: {{ template "prometheus.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus.name" . }}
  namespace: {{ .Values.namespace }}
