apiVersion: v1
kind: Secret
metadata:
  name: etcd-certs
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{ $root := .}}
{{ range $path, $bytes := .Files.Glob "etcd-certs/*" }}
{{ base $path | indent 2 }}: '{{ $root.Files.Get $path | b64enc }}'
{{ end }}
