name: "Build: component-manage"

on:
  workflow_dispatch:
  push:
    tags:
      - 'component-manage/v*'

jobs:
  versions:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get Version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/component-manage/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/component-manage/v}
            TAG=$VERSION
            echo "🚀 Release version: $VERSION"
          else
            SHORT_SHA=${GITHUB_SHA:0:7}
            VERSION="0.0.0-snapshot.${SHORT_SHA}"
            TAG="snapshot.${SHORT_SHA}"
            echo "🔧 Snapshot version: $VERSION"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  build:
    needs: versions
    strategy:
      matrix:
        name:
        - component-manage
        include:
        - name: component-manage
          workdir: ./component-manage
          target: build-result

    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      # id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # to push the built image to GitHub Container Registry
    with:
      context: ${{ matrix.workdir }}
      target: ${{ matrix.target }}
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      set-meta-annotations: true
      cache: true
      cache-mode: max
      sign: false
      meta-tags: |
        type=raw,value=${{ needs.versions.outputs.tag }}
      meta-images: |
        ghcr.io/${{ github.repository }}/${{ matrix.name }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
  chart:
    needs: [versions, build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Modify values.yaml
        env:
          VALUES_FILE: component-manage/chart/component-manage/values.yaml
        run: |
          yq -i '.image.tag="${{ needs.versions.outputs.tag }}"'                  ${{ env.VALUES_FILE }}
          yq -i '.image.repository="${{ github.repository }}/component-manage"'   ${{ env.VALUES_FILE }}
          yq -i '.image.registry="ghcr.io"'                                       ${{ env.VALUES_FILE }}

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: component-manage
          registry: ghcr.io
          repository: ${{ github.repository_owner }}/charts
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.versions.outputs.version }}
          path: component-manage/chart/component-manage


